### ISSUE TITLE
Error in Deployment

### ISSUE THREAD

**Issue by ehsan235** [khast3x/Redcloud#11] opened 2019-12-18 10:53 UTC
Installing docker
[~] This might take a few minutes... Hang in there!
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/debian kali-rolling stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
E: The repository 'https://download.docker.com/linux/debian kali-rolling Release' does not have a Release file.
[!] Something went wrong with running command
Command '['sh', 'get-docker.sh']' returned non-zero exit status 100.
Traceback (most recent call last):
  File "redcloud.py", line 418, in <module>
    menu_deploy_target()
  File "redcloud.py", line 368, in menu_deploy_target
    deploy_local()
  File "redcloud.py", line 156, in deploy_local
    install_docker()
  File "redcloud.py", line 119, in install_docker
    output += run_cmd_output(DOCKER_INSTALL2)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by pieterhouwen** [comment] 2020-01-07 18:06
Duplicate of issue #10 

Use the Kali docker.io package and skip the docker installation.

**Closed** 2021-02-11 22:48 UTC
